-- =============================================================
-- 018_implausibility_bounds_full.sql  (ADDITIVE — UPDATE only)
-- Extend the implausibility BOUND (migration 017) to EVERY in-use metric.
-- Generated by scripts/gen_018_bounds.py, which asserts against live data:
--   * COVERAGE   — bounds cover exactly the 127 in-use, still-unbounded metrics.
--   * CONTAINMENT — every value stored in biomarkers sits STRICTLY inside its new
--                   [plausible_min, plausible_max] with headroom (no real value gated).
-- Bounds are WIDE physiological extremes: a real (even pathological) value passes;
-- a 10-100x OCR/unit/comma slip is caught and routed to staging. These are NOT
-- clinical reference ranges (those stay in min_value/max_value and only flag).
-- =============================================================
BEGIN;

UPDATE public.metric_definitions AS m
SET    plausible_min = v.pmin, plausible_max = v.pmax
FROM (VALUES
  ('afp', 0, 1000000),
  ('albumin', 0.5, 8),
  ('albumin_globulin_ratio', 0.1, 20),
  ('albumin_urine', 0, 100000),
  ('alp', 5, 10000),
  ('alt', 1, 50000),
  ('amylase', 1, 100000),
  ('anti_hbs_titre', 0, 100000),
  ('anti_hcv', 0, 10000),
  ('apo_a1', 10, 500),
  ('apo_b', 5, 600),
  ('apo_b_a1_ratio', 0.01, 10),
  ('arms_fat_pct', 0.5, 80),
  ('ast', 1, 50000),
  ('ast_alt_ratio', 0.05, 50),
  ('basophils_abs', 0, 5),
  ('basophils_pct', 0, 100),
  ('bicarbonate', 3, 60),
  ('bilirubin', 0.05, 100),
  ('bilirubin_direct', 0.01, 80),
  ('bilirubin_indirect', 0.01, 80),
  ('bmc_kg', 0.1, 10),
  ('bmc_total', 100, 6000),
  ('bmd_femur_mean', 0.1, 3.0),
  ('bmd_femur_neck_left', 0.1, 3.0),
  ('bmd_femur_neck_right', 0.1, 3.0),
  ('bmd_femur_total_left', 0.1, 3.0),
  ('bmd_femur_total_right', 0.1, 3.0),
  ('bmd_spine_l1_l4', 0.1, 3.0),
  ('bmd_total_body', 0.1, 3.0),
  ('bmi', 8, 100),
  ('bun', 1, 500),
  ('bun_creatinine_ratio', 0.5, 200),
  ('calcium', 3, 25),
  ('cea', 0, 1000000),
  ('chloride', 50, 160),
  ('ck', 1, 1000000),
  ('coronary_calcium_score', 0, 20000),
  ('cortisol_am', 0.1, 300),
  ('creatinine', 0.1, 25),
  ('creatinine_urine', 0.5, 5000),
  ('crp', 0, 1000),
  ('dheas', 1, 3000),
  ('diastolic_bp', 20, 200),
  ('eag', 20, 800),
  ('egfr', 1, 250),
  ('eosinophils_abs', 0, 30),
  ('eosinophils_pct', 0, 100),
  ('esr', 0, 200),
  ('fat_free_mass_kg', 5, 150),
  ('fat_mass_kg', 0.5, 200),
  ('ferritin', 0, 200000),
  ('folate', 0.1, 100),
  ('free_t3', 0.1, 50),
  ('free_t4', 0.05, 30),
  ('fsh', 0.1, 1000),
  ('g6pd', 0, 100),
  ('ggt', 1, 20000),
  ('globulin', 0.5, 15),
  ('hbsag', 0, 10000),
  ('hemoglobin', 3, 25),
  ('homa_ir', 0.05, 200),
  ('homocysteine', 1, 500),
  ('hscrp', 0, 1000),
  ('ige', 0, 1000000),
  ('igf1', 5, 3000),
  ('iron', 1, 2000),
  ('ldh', 10, 100000),
  ('legs_fat_pct', 0.5, 80),
  ('lh', 0.1, 1000),
  ('lipase', 1, 100000),
  ('lpa', 0, 2000),
  ('lung_age', 1, 150),
  ('lymphocytes_abs', 0, 200),
  ('lymphocytes_pct', 0, 100),
  ('magnesium_serum', 0.3, 15),
  ('mch', 5, 60),
  ('mchc', 15, 50),
  ('mcv', 40, 160),
  ('mentzer_index', 0, 100),
  ('monocytes_abs', 0, 30),
  ('monocytes_pct', 0, 100),
  ('mpv', 3, 25),
  ('neutrophils_abs', 0, 300),
  ('neutrophils_pct', 0, 100),
  ('pcv', 10, 70),
  ('phosphorus', 0.3, 25),
  ('platelet_count', 1, 5000),
  ('potassium', 1, 12),
  ('prolactin', 0.5, 100000),
  ('psa', 0, 100000),
  ('pth_intact', 1, 10000),
  ('rbc', 1, 10),
  ('rdw', 5, 70),
  ('resting_hr_spot', 20, 300),
  ('rheumatoid_factor', 0, 100000),
  ('shbg', 1, 1000),
  ('sodium', 90, 200),
  ('subcutaneous_fat_area', 1, 3000),
  ('systolic_bp', 40, 300),
  ('tibc', 50, 1500),
  ('tlc', 0, 1000),
  ('total_cholesterol', 20, 1000),
  ('total_protein', 1, 15),
  ('transferrin_saturation', 0, 150),
  ('trunk_fat_pct', 0.5, 80),
  ('tscore_femur_mean', -10, 10),
  ('tscore_femur_neck_left', -10, 10),
  ('tscore_femur_neck_right', -10, 10),
  ('tscore_femur_total_left', -10, 10),
  ('tscore_femur_total_right', -10, 10),
  ('tscore_spine_l1_l4', -10, 10),
  ('tscore_total_body', -10, 10),
  ('tsh', 0.001, 150),
  ('uibc', 5, 1500),
  ('urea', 1, 1000),
  ('uric_acid', 0.1, 30),
  ('urine_acr', 0, 100000),
  ('urine_ph', 4, 9.5),
  ('urine_specific_gravity', 1.0, 1.07),
  ('visceral_fat_area_ct', 1, 2000),
  ('visceral_fat_mass', 1, 20000),
  ('vitamin_b12', 30, 200000),
  ('vo2max_estimated', 3, 100),
  ('vo2max_lab', 3, 100),
  ('wbc', 0, 1000),
  ('zinc', 5, 2000)
) AS v(name, pmin, pmax)
WHERE m.name = v.name
  AND m.plausible_min IS NULL AND m.plausible_max IS NULL;   -- don't clobber 017's bounds

DO $$
DECLARE
    n_unbounded_inuse int;
BEGIN
    SELECT count(*) INTO n_unbounded_inuse
    FROM public.metric_definitions md
    WHERE md.plausible_min IS NULL AND md.plausible_max IS NULL
      AND EXISTS (SELECT 1 FROM public.biomarkers b WHERE b.metric_definition_id = md.id);
    RAISE NOTICE '018: in-use metrics still UNBOUNDED after this migration: % (expect 0)', n_unbounded_inuse;
    IF n_unbounded_inuse <> 0 THEN
        RAISE EXCEPTION '018: % in-use metrics remain unbounded — aborting', n_unbounded_inuse;
    END IF;
END $$;

COMMIT;
